version: '3.4'

networks:
  dev:
    driver: bridge

services:
  configs:
    image: ${DOCKER_REGISTRY-}configs
    build:
      context: .
      dockerfile: ConfigurationAPI\Dockerfile
    depends_on:
        - postgres
    networks:
          - dev
  openapi:
    image: ${DOCKER_REGISTRY-}openapi
    build:
      context: .
      dockerfile: OpenAPI/Dockerfile
    depends_on:
      - configs
    networks:
        - dev

  postgres:
    container_name: postgres_container
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgadmin
      PGDATA: /data/postgres
      POSTGRES_DB: cholecystitis
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always
    networks:
        - dev

  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@cholecystitis.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: always
    networks:
        - dev

  prometheus:
    image: prom/prometheus
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - 9090:9090
    restart: always
    networks:
        - dev

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: always
    networks:
        - dev
  

volumes:
    postgres:
    pgadmin:
