global:
  scrape_interval:     10s
  evaluation_interval: 30s
scrape_configs:
  - job_name: 'openApi'
    scrape_interval: 5s
    scheme: http # You may have to change this to 'http'
                  # or you'd have to create a certificate 
                  # with `host.docker.internal`
    static_configs:
         - targets: ['host.docker.internal:5000']